# Generated by Django 4.1.6 on 2023-03-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_expence_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='tax_pct',
            field=models.IntegerField(default=5),
        ),
    ]
