# Generated by Django 4.1.6 on 2023-03-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_branch_tax_pct_business_tax_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='date_enterd',
            field=models.DateTimeField(),
        ),
    ]
