# Generated by Django 4.1.6 on 2023-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_student_alter_messages_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='date_enterd',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
