# Generated by Django 4.1.6 on 2023-05-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_profit_date_enterd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
